version: '3.8'

services:
  autenticacion:
    build:
      context: ./services
      dockerfile: autenticacion
    depends_on:
      - database
    ports:
      - "8080:8080"

  solicitudes:
    build:
      context: ./services
      dockerfile: solicitudes
    depends_on:
      - database
    ports:
      - "8081:8081"

  database:
    build:
      context: ./database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=/run/secrets/database
    secrets:
      - database
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  database:
    file: ./secrets/database.txt
